// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBktImDf40dSn-4FnuIsw3bb7hrmJ1o6zo',
    appId: '1:1041105145243:web:0217b4de8f84280bee253e',
    messagingSenderId: '1041105145243',
    projectId: 'todo-app-98d93',
    authDomain: 'todo-app-98d93.firebaseapp.com',
    storageBucket: 'todo-app-98d93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIKf8E_F2wO30xwQRN-eAFLSfWoldpSGA',
    appId: '1:1041105145243:android:35f9675f0727704cee253e',
    messagingSenderId: '1041105145243',
    projectId: 'todo-app-98d93',
    storageBucket: 'todo-app-98d93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXyPPNHNuXbVR2kTK-N-KoBUsxkHnr03I',
    appId: '1:1041105145243:ios:76aaa4e586b45c43ee253e',
    messagingSenderId: '1041105145243',
    projectId: 'todo-app-98d93',
    storageBucket: 'todo-app-98d93.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXyPPNHNuXbVR2kTK-N-KoBUsxkHnr03I',
    appId: '1:1041105145243:ios:76aaa4e586b45c43ee253e',
    messagingSenderId: '1041105145243',
    projectId: 'todo-app-98d93',
    storageBucket: 'todo-app-98d93.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBktImDf40dSn-4FnuIsw3bb7hrmJ1o6zo',
    appId: '1:1041105145243:web:424eb3eac473bbfeee253e',
    messagingSenderId: '1041105145243',
    projectId: 'todo-app-98d93',
    authDomain: 'todo-app-98d93.firebaseapp.com',
    storageBucket: 'todo-app-98d93.appspot.com',
  );
}
